# Generated by Django 4.2.17 on 2024-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
